version: '3'
services:
  python:
    build: .
    volumes:
      - /home/guillaumer/aimlx/neural-editor-grll:/code
      - /home/guillaumer/aimlx/neural-editor-grll-data:/data
    environment:
      - CUDA_VISIBLE_DEVICES=0
